name: Teste Clima Agendado

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Rodar script de clima
        run: python clima_horario.py
